version: '3.9'

services:
  api:
    build: .
    container_name: ai-knowledge-api
    restart: always
    depends_on:
      - redis
    environment:
      DATABASE_URL: postgresql://neondb_owner:npg_WQVAJ3GmbwH1@ep-raspy-credit-a4erv7me-pooler.us-east-1.aws.neon.tech/ai-research?sslmode=require&pgbouncer=true
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: StrongPassword123
    ports:
      - '3000:3000'

  redis:
    image: redis:7-alpine
    container_name: ai-knowledge-redis
    restart: always
    command: redis-server --appendonly yes --requirepass StrongPassword123